
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/03_minibatch_training.ipynb
from exp.nb_02 import *
import torch.nn.functional as F
import torch.nn as nn

def accuracy(out, yb): return (torch.argmax(out, dim=1) == yb).float().mean()

from torch import optim

class Dataset():
    def __init__(self, x, y): self.x, self.y = x, y
    def __len__(self): return len(self.x)
    def __getitem__(self, i): return self.x[i], self.y[i]